# Generated by Django 6.0.1 on 2026-02-07 15:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonChua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bon', models.CharField(max_length=50)),
                ('loai_nhien_lieu', models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('DO', 'Dầu DO')], max_length=10)),
                ('suc_chua_toi_da', models.FloatField()),
                ('muc_hien_tai', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ncc', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255)),
                ('sdt', models.CharField(max_length=15)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('anh_bia', models.CharField(max_length=500)),
                ('tom_tat', models.TextField()),
                ('noi_dung', models.TextField()),
                ('ngay_dang', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TramXang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tram', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('staff', 'Nhân viên bán hàng')], default='staff', max_length=10)),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(blank=True, max_length=20, null=True)),
                ('ca_lam_viec', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hd', models.CharField(max_length=50, unique=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.FloatField()),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mat_hang', models.CharField(max_length=100)),
                ('so_luong', models.FloatField()),
                ('don_gia', models.FloatField()),
                ('thanh_tien', models.FloatField()),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_pn', models.CharField(max_length=20, unique=True)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('so_lit_nhap', models.FloatField()),
                ('thanh_tien', models.FloatField()),
                ('bon_chua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bonchua')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sp', models.CharField(max_length=100)),
                ('gia_tham_khao', models.FloatField()),
                ('anh_sp', models.CharField(max_length=500)),
                ('mo_ta', models.TextField()),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.danhmuc')),
            ],
        ),
        migrations.AddField(
            model_name='bonchua',
            name='tram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tramxang'),
        ),
    ]
