# Generated by Django 6.0.3 on 2026-03-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tram_xang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhan_vien_truc_thuoc', to='core.tramxang', verbose_name='Trạm trực thuộc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ca_lam_viec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cccd',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CCCD'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Giám đốc / Quản trị viên'), ('tram_truong', 'Cửa hàng trưởng'), ('staff', 'Nhân viên bán hàng')], default='staff', max_length=20, verbose_name='Chức vụ'),
        ),
    ]
