# Generated by Django 6.0.1 on 2026-03-17 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_tram_xang_alter_user_ca_lam_viec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YeuCauNhapHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_nhien_lieu', models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('DO', 'Dầu DO')], max_length=10)),
                ('so_luong', models.FloatField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('cho_duyet', 'Đang chờ duyệt'), ('da_duyet', 'Đã duyệt & Đang giao'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_yeu_cau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tramxang')),
            ],
        ),
    ]
