# Generated by Django 6.0.3 on 2026-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yeucaunhaphang'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangGiaNhienLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_nhien_lieu', models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('DO', 'Dầu DO')], max_length=10, unique=True, verbose_name='Loại Xăng Dầu')),
                ('gia_ban', models.FloatField(verbose_name='Giá bán hiện tại (VNĐ/Lít)')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
