# Generated by Django 6.0.3 on 2026-03-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banggianhienlieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banggianhienlieu',
            name='loai_nhien_lieu',
            field=models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('E10', 'Xăng Sinh Học E10'), ('DO', 'Dầu DO')], max_length=10, unique=True, verbose_name='Loại Xăng Dầu'),
        ),
        migrations.AlterField(
            model_name='bonchua',
            name='loai_nhien_lieu',
            field=models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('E10', 'Xăng Sinh Học E10'), ('DO', 'Dầu DO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='yeucaunhaphang',
            name='loai_nhien_lieu',
            field=models.CharField(choices=[('A95', 'Xăng A95'), ('E5', 'Xăng E5'), ('E10', 'Xăng Sinh Học E10'), ('DO', 'Dầu DO')], max_length=10),
        ),
    ]
