# Generated by Django 6.0.3 on 2026-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_banggianhienlieu_loai_nhien_lieu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phieunhap",
            name="cuoc_van_chuyen",
            field=models.FloatField(
                default=0, help_text="Cước xe bồn (dựa trên số Km)"
            ),
        ),
        migrations.AddField(
            model_name="phieunhap",
            name="gia_nhap_1_lit",
            field=models.FloatField(default=0, help_text="Giá mua sỉ từ Kho"),
        ),
        migrations.AddField(
            model_name="phieunhap",
            name="tong_chi_phi",
            field=models.FloatField(default=0, help_text="Tiền hàng + Cước vận chuyển"),
        ),
    ]
