# Generated by Django 6.0.3 on 2026-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_phieunhap_cuoc_van_chuyen_phieunhap_gia_nhap_1_lit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nhacungcap",
            name="ton_kho_A95",
            field=models.FloatField(default=500000),
        ),
        migrations.AddField(
            model_name="nhacungcap",
            name="ton_kho_DO",
            field=models.FloatField(default=500000),
        ),
        migrations.AddField(
            model_name="nhacungcap",
            name="ton_kho_E10",
            field=models.FloatField(default=500000),
        ),
        migrations.AddField(
            model_name="nhacungcap",
            name="ton_kho_E5",
            field=models.FloatField(default=500000),
        ),
    ]
