# Generated by Django 6.0.3 on 2026-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_nhacungcap_ton_kho_a95_nhacungcap_ton_kho_do_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tintuc",
            name="anh_bia",
            field=models.ImageField(
                blank=True, null=True, upload_to="tin_tuc/anh_bia/"
            ),
        ),
    ]
