# Generated by Django 6.0.3 on 2026-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_tintuc_anh_bia"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="anh_sp",
            field=models.ImageField(blank=True, null=True, upload_to="san_pham/"),
        ),
    ]
