# Generated by Django 6.0.3 on 2026-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_avatar_alter_sanpham_anh_sp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerTrangChu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_chien_dich",
                    models.CharField(max_length=100, verbose_name="Tên chiến dịch"),
                ),
                (
                    "anh_banner",
                    models.ImageField(upload_to="banners/", verbose_name="Ảnh Banner"),
                ),
                (
                    "tieu_de_chinh",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Tiêu đề chính (Chữ lớn)",
                    ),
                ),
                (
                    "tieu_de_phu",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tiêu đề phụ (Chữ nhỏ)"
                    ),
                ),
                (
                    "dang_hien_thi",
                    models.BooleanField(
                        default=False, verbose_name="Đang hiển thị trên trang chủ?"
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
