# Generated by Django 6.0.3 on 2026-04-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_bannertrangchu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tintuc",
            options={
                "verbose_name": "Tin Tức",
                "verbose_name_plural": "Quản lý Tin Tức",
            },
        ),
    ]
