# Generated by Django 6.0.3 on 2026-04-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_danhgiasanpham"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Giám đốc / Quản trị viên"),
                    ("ke_toan", "Kế toán nội bộ"),
                    ("truong_tram", "Cửa hàng trưởng / Trưởng trạm"),
                    ("nv_ban_hang", "Nhân viên bán hàng (Siêu thị)"),
                    ("nv_ban_xang", "Nhân viên bơm xăng"),
                ],
                default="nv_ban_xang",
                max_length=20,
                verbose_name="Chức vụ",
            ),
        ),
    ]
