# Generated by Django 6.0.3 on 2026-04-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banggianhienlieu",
            options={
                "verbose_name": "Bảng Giá Nhiên Liệu",
                "verbose_name_plural": "Bảng Giá Hệ Thống",
            },
        ),
        migrations.AlterModelOptions(
            name="bonchua",
            options={
                "verbose_name": "Bồn Chứa",
                "verbose_name_plural": "2. Quản lý Bồn Chứa",
            },
        ),
        migrations.AlterModelOptions(
            name="hoadon",
            options={
                "verbose_name": "Hóa Đơn",
                "verbose_name_plural": "3. Lịch sử Hóa Đơn",
            },
        ),
        migrations.AlterModelOptions(
            name="nhacungcap",
            options={
                "verbose_name": "Kho Tổng / NCC",
                "verbose_name_plural": "4. Quản lý Kho Tổng",
            },
        ),
        migrations.AlterModelOptions(
            name="phieunhap",
            options={
                "verbose_name": "Phiếu Điều Phối",
                "verbose_name_plural": "5. Phiếu Điều Phối (Lịch sử)",
            },
        ),
        migrations.AlterModelOptions(
            name="tramxang",
            options={
                "verbose_name": "Trạm Xăng",
                "verbose_name_plural": "1. Quản lý Trạm Xăng",
            },
        ),
        migrations.AlterField(
            model_name="bannertrangchu",
            name="dang_hien_thi",
            field=models.BooleanField(default=False, verbose_name="Đang hiển thị?"),
        ),
        migrations.AlterField(
            model_name="bannertrangchu",
            name="tieu_de_chinh",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tiêu đề chính"
            ),
        ),
        migrations.AlterField(
            model_name="bannertrangchu",
            name="tieu_de_phu",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tiêu đề phụ"
            ),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="loai_nhien_lieu",
            field=models.CharField(
                choices=[
                    ("A95", "Xăng A95"),
                    ("E5", "Xăng E5"),
                    ("E10", "Xăng Sinh Học E10"),
                    ("DO", "Dầu DO"),
                ],
                max_length=10,
                verbose_name="Loại nhiên liệu",
            ),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="muc_hien_tai",
            field=models.FloatField(verbose_name="Mức hiện tại (Lít)"),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="suc_chua_toi_da",
            field=models.FloatField(verbose_name="Sức chứa tối đa (Lít)"),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="ten_bon",
            field=models.CharField(max_length=50, verbose_name="Tên Bồn"),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="tram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tramxang",
                verbose_name="Thuộc Trạm",
            ),
        ),
        migrations.AlterField(
            model_name="danhmucmart",
            name="ten_danh_muc",
            field=models.CharField(max_length=100, verbose_name="Tên Danh Mục"),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="ma_hd",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã HĐ"),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="nhan_vien",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Nhân viên thu ngân",
            ),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="thoi_gian",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="tong_tien",
            field=models.FloatField(verbose_name="Tổng tiền"),
        ),
        migrations.AlterField(
            model_name="hosoungvien",
            name="file_cv",
            field=models.FileField(upload_to="cv_ung_vien/", verbose_name="File CV"),
        ),
        migrations.AlterField(
            model_name="lienhegopy",
            name="noi_dung",
            field=models.TextField(verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="dia_chi",
            field=models.CharField(max_length=255, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="latitude",
            field=models.FloatField(verbose_name="Vĩ độ"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="longitude",
            field=models.FloatField(verbose_name="Kinh độ"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="sdt",
            field=models.CharField(max_length=15, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ten_ncc",
            field=models.CharField(max_length=100, verbose_name="Tên Kho / NCC"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ton_kho_A95",
            field=models.FloatField(default=500000, verbose_name="Tồn kho A95"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ton_kho_DO",
            field=models.FloatField(default=500000, verbose_name="Tồn kho DO"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ton_kho_E10",
            field=models.FloatField(default=500000, verbose_name="Tồn kho E10"),
        ),
        migrations.AlterField(
            model_name="nhacungcap",
            name="ton_kho_E5",
            field=models.FloatField(default=500000, verbose_name="Tồn kho E5"),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="bon_chua",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bonchua",
                verbose_name="Nhập vào Bồn",
            ),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="ma_pn",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mã Phiếu Nhập"
            ),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="nha_cung_cap",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.nhacungcap",
                verbose_name="Từ Kho Tổng",
            ),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="so_lit_nhap",
            field=models.FloatField(verbose_name="Số lít"),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="thanh_tien",
            field=models.FloatField(verbose_name="Tiền hàng"),
        ),
        migrations.AlterField(
            model_name="phieunhap",
            name="thoi_gian",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày xuất"),
        ),
        migrations.AlterField(
            model_name="tramxang",
            name="dia_chi",
            field=models.CharField(max_length=255, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="tramxang",
            name="latitude",
            field=models.FloatField(verbose_name="Vĩ độ (Latitude)"),
        ),
        migrations.AlterField(
            model_name="tramxang",
            name="longitude",
            field=models.FloatField(verbose_name="Kinh độ (Longitude)"),
        ),
        migrations.AlterField(
            model_name="tramxang",
            name="ten_tram",
            field=models.CharField(max_length=100, verbose_name="Tên Trạm"),
        ),
    ]
