# Generated by Django 6.0.3 on 2026-04-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_banggianhienlieu_options_alter_bonchua_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhMucDichVu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_danh_muc",
                    models.CharField(
                        max_length=100,
                        verbose_name="Tên Danh Mục (VD: GSMS Mart, Rửa Xe, Cafe)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Danh mục SP & Dịch vụ",
                "verbose_name_plural": "6. Danh mục SP & Dịch vụ",
            },
        ),
        migrations.RemoveField(
            model_name="sanphammart",
            name="danh_muc",
        ),
        migrations.CreateModel(
            name="SanPhamDichVu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_hinh",
                    models.CharField(
                        choices=[
                            ("san_pham", "Sản phẩm vật lý (Có tồn kho)"),
                            ("dich_vu", "Dịch vụ (Không tính tồn kho)"),
                        ],
                        default="san_pham",
                        max_length=20,
                        verbose_name="Phân loại",
                    ),
                ),
                (
                    "ten_dich_vu",
                    models.CharField(
                        max_length=100, verbose_name="Tên Sản phẩm / Dịch vụ"
                    ),
                ),
                ("gia_ban", models.FloatField(verbose_name="Giá thu khách (VNĐ)")),
                (
                    "ton_kho",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Bỏ trống nếu là Dịch vụ",
                        null=True,
                    ),
                ),
                (
                    "anh_minh_hoa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dich_vu/",
                        verbose_name="Ảnh minh họa",
                    ),
                ),
                (
                    "danh_muc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.danhmucdichvu",
                        verbose_name="Thuộc danh mục",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm & Dịch vụ",
                "verbose_name_plural": "7. Quản lý SP & Dịch vụ",
            },
        ),
        migrations.DeleteModel(
            name="DanhMucMart",
        ),
        migrations.DeleteModel(
            name="SanPhamMart",
        ),
    ]
