# Generated by Django 6.0.3 on 2026-04-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_danhmucdichvu_remove_sanphammart_danh_muc_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banggianhienlieu",
            options={
                "verbose_name": "Bảng Giá Nhiên Liệu",
                "verbose_name_plural": "8. Bảng Giá Hệ Thống",
            },
        ),
        migrations.AlterModelOptions(
            name="bannertrangchu",
            options={
                "verbose_name": "Banner Trang Chủ",
                "verbose_name_plural": "Quản lý Banner",
            },
        ),
        migrations.AlterModelOptions(
            name="chitiethoadon",
            options={
                "verbose_name": "Chi tiết HĐ",
                "verbose_name_plural": "Chi tiết Hóa Đơn",
            },
        ),
        migrations.AlterModelOptions(
            name="danhgiasanpham",
            options={
                "verbose_name": "Đánh giá của Khách",
                "verbose_name_plural": "Quản lý Đánh giá",
            },
        ),
        migrations.AlterModelOptions(
            name="danhmuc",
            options={
                "verbose_name": "Danh mục Sỉ B2B",
                "verbose_name_plural": "9. Danh mục Hàng Sỉ (B2B)",
            },
        ),
        migrations.AlterModelOptions(
            name="danhmucdichvu",
            options={
                "verbose_name": "Danh mục SP & Dịch vụ",
                "verbose_name_plural": "6. Danh mục SP & DV (Trạm)",
            },
        ),
        migrations.AlterModelOptions(
            name="sanpham",
            options={
                "verbose_name": "Sản phẩm Sỉ B2B",
                "verbose_name_plural": "10. Quản lý Hàng Sỉ (B2B)",
            },
        ),
        migrations.AlterModelOptions(
            name="sanphamdichvu",
            options={
                "verbose_name": "Sản phẩm & Dịch vụ",
                "verbose_name_plural": "7. Quản lý SP & DV (Trạm)",
            },
        ),
        migrations.AlterModelOptions(
            name="tintuc",
            options={
                "verbose_name": "Tin Tức & Sự Kiện",
                "verbose_name_plural": "Quản lý Tin Tức",
            },
        ),
        migrations.AlterModelOptions(
            name="yeucaunhaphang",
            options={
                "verbose_name": "Yêu cầu Nhập hàng",
                "verbose_name_plural": "11. Yêu cầu Nhập hàng",
            },
        ),
        migrations.AddField(
            model_name="hoadon",
            name="phuong_thuc_thanh_toan",
            field=models.CharField(
                choices=[
                    ("tien_mat", "Tiền mặt"),
                    ("chuyen_khoan", "Chuyển khoản / Momo"),
                    ("the", "Quẹt thẻ POS"),
                ],
                default="tien_mat",
                max_length=20,
                verbose_name="Thanh toán bằng",
            ),
        ),
        migrations.AddField(
            model_name="tramxang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("hoat_dong", "Đang hoạt động"),
                    ("bao_tri", "Đang bảo trì / Đóng cửa"),
                ],
                default="hoat_dong",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="chitiethoadon",
            name="don_gia",
            field=models.FloatField(verbose_name="Đơn giá"),
        ),
        migrations.AlterField(
            model_name="chitiethoadon",
            name="hoa_don",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.hoadon",
                verbose_name="Thuộc Hóa Đơn",
            ),
        ),
        migrations.AlterField(
            model_name="chitiethoadon",
            name="so_luong",
            field=models.FloatField(verbose_name="Số lượng"),
        ),
        migrations.AlterField(
            model_name="chitiethoadon",
            name="ten_mat_hang",
            field=models.CharField(max_length=100, verbose_name="Tên hàng / Dịch vụ"),
        ),
        migrations.AlterField(
            model_name="chitiethoadon",
            name="thanh_tien",
            field=models.FloatField(verbose_name="Thành tiền"),
        ),
        migrations.AlterField(
            model_name="danhgiasanpham",
            name="da_duyet",
            field=models.BooleanField(default=False, verbose_name="Đã duyệt hiển thị"),
        ),
        migrations.AlterField(
            model_name="danhgiasanpham",
            name="san_pham",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_danh_gia",
                to="core.sanpham",
                verbose_name="Sản phẩm được đánh giá",
            ),
        ),
        migrations.AlterField(
            model_name="danhmuc",
            name="ten_dm",
            field=models.CharField(max_length=100, verbose_name="Tên Danh mục (Sỉ)"),
        ),
        migrations.AlterField(
            model_name="danhmucdichvu",
            name="ten_danh_muc",
            field=models.CharField(max_length=100, verbose_name="Tên Danh Mục"),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="anh_sp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="san_pham/",
                verbose_name="Ảnh sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="danh_muc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.danhmuc",
                verbose_name="Thuộc danh mục",
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="gia_tham_khao",
            field=models.FloatField(verbose_name="Giá tham khảo"),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="mo_ta",
            field=models.TextField(verbose_name="Mô tả chi tiết"),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="ten_sp",
            field=models.CharField(max_length=100, verbose_name="Tên sản phẩm sỉ"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="anh_bia",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tin_tuc/anh_bia/",
                verbose_name="Ảnh bìa",
            ),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="ngay_dang",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="noi_dung",
            field=models.TextField(verbose_name="Nội dung chi tiết"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="tieu_de",
            field=models.CharField(max_length=200, verbose_name="Tiêu đề bài viết"),
        ),
        migrations.AlterField(
            model_name="tintuc",
            name="tom_tat",
            field=models.TextField(verbose_name="Tóm tắt ngắn"),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="ghi_chu",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="loai_nhien_lieu",
            field=models.CharField(
                choices=[
                    ("A95", "Xăng A95"),
                    ("E5", "Xăng E5"),
                    ("E10", "Xăng Sinh Học E10"),
                    ("DO", "Dầu DO"),
                ],
                max_length=10,
                verbose_name="Loại nhiên liệu",
            ),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="nguoi_yeu_cau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người gửi",
            ),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="so_luong",
            field=models.FloatField(verbose_name="Số lượng (Lít)"),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="thoi_gian",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian gửi"),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="tram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tramxang",
                verbose_name="Trạm yêu cầu",
            ),
        ),
        migrations.AlterField(
            model_name="yeucaunhaphang",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("cho_duyet", "Đang chờ duyệt"),
                    ("da_duyet", "Đã duyệt & Đang giao"),
                    ("tu_choi", "Từ chối"),
                ],
                default="cho_duyet",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
    ]
