# Generated by Django 6.0.3 on 2026-04-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_banggianhienlieu_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonchua",
            name="loai_san_pham",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sanpham",
                verbose_name="Thuộc sản phẩm Catalog",
            ),
        ),
        migrations.AlterField(
            model_name="bonchua",
            name="loai_nhien_lieu",
            field=models.CharField(
                choices=[
                    ("A95", "Xăng A95"),
                    ("E5", "Xăng E5"),
                    ("E10", "Xăng Sinh Học E10"),
                    ("DO", "Dầu DO"),
                ],
                max_length=10,
                verbose_name="Mã định danh (A95/E5/DO)",
            ),
        ),
    ]
