# Generated by Django 6.0.3 on 2026-04-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_bonchua_loai_san_pham_alter_bonchua_loai_nhien_lieu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BannerTrangChu",
        ),
    ]
