# Generated by Django 6.0.3 on 2026-04-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_delete_bannertrangchu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sanphamdichvu",
            name="danh_muc",
        ),
        migrations.AlterModelOptions(
            name="danhgiasanpham",
            options={
                "verbose_name": "Đánh giá của Khách",
                "verbose_name_plural": "11. Quản lý Đánh giá",
            },
        ),
        migrations.AlterModelOptions(
            name="danhmuc",
            options={
                "verbose_name": "Danh mục Sản phẩm",
                "verbose_name_plural": "6. Danh mục Catalog",
            },
        ),
        migrations.AlterModelOptions(
            name="doitacb2b",
            options={
                "verbose_name": "Yêu cầu Hợp tác",
                "verbose_name_plural": "12. Quản lý Hợp tác B2B",
            },
        ),
        migrations.AlterModelOptions(
            name="hosoungvien",
            options={
                "verbose_name": "Hồ sơ Ứng viên",
                "verbose_name_plural": "13. Quản lý Tuyển dụng",
            },
        ),
        migrations.AlterModelOptions(
            name="lienhegopy",
            options={
                "verbose_name": "Liên hệ / Góp ý",
                "verbose_name_plural": "14. Quản lý Góp ý Khách hàng",
            },
        ),
        migrations.AlterModelOptions(
            name="sanpham",
            options={
                "verbose_name": "Sản phẩm Trưng bày",
                "verbose_name_plural": "7. Quản lý Sản phẩm (Catalog)",
            },
        ),
        migrations.AlterModelOptions(
            name="tintuc",
            options={
                "verbose_name": "Tin Tức & Sự Kiện",
                "verbose_name_plural": "10. Quản lý Tin Tức",
            },
        ),
        migrations.AlterModelOptions(
            name="yeucaunhaphang",
            options={
                "verbose_name": "Yêu cầu Nhập hàng",
                "verbose_name_plural": "9. Yêu cầu Nhập hàng",
            },
        ),
        migrations.AddField(
            model_name="lienhegopy",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="danhmuc",
            name="ten_dm",
            field=models.CharField(max_length=100, verbose_name="Tên Danh mục"),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="anh_sp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="san_pham/",
                verbose_name="Ảnh minh họa",
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="mo_ta",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mô tả chi tiết"
            ),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="ten_sp",
            field=models.CharField(
                max_length=100, verbose_name="Tên Sản phẩm / Dịch vụ"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Giám đốc / Quản trị viên"),
                    ("ke_toan", "Kế toán nội bộ"),
                    ("truong_tram", "Cửa hàng trưởng / Trưởng trạm"),
                    ("nv_ban_xang", "Nhân viên bơm xăng"),
                ],
                default="nv_ban_xang",
                max_length=20,
                verbose_name="Chức vụ",
            ),
        ),
        migrations.DeleteModel(
            name="DanhMucDichVu",
        ),
        migrations.DeleteModel(
            name="SanPhamDichVu",
        ),
    ]
