# Generated by Django 6.0.3 on 2026-04-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_sanphamdichvu_danh_muc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhGiaTram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_khach_hang", models.CharField(max_length=100)),
                ("so_sao", models.IntegerField(default=5)),
                ("noi_dung", models.TextField()),
                ("da_duyet", models.BooleanField(default=False)),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                (
                    "tram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cac_danh_gia",
                        to="core.tramxang",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DanhGiaSanPham",
        ),
    ]
